s = set()

number = int(input("Enter a number :"))
s.add(int(number))
number = int(input("Enter a number :"))
s.add(int(number))
number= int(input("Enter a number :"))
s.add(int(number))
number = int(input("Enter a number :"))
s.add(int(number))
number = int(input("Enter a number :"))
s.add(int(number))
number = int(input("Enter a number :"))
s.add(int(number))
number = int(input("Enter a number :"))
s.add(int(number))
number = int(input("Enter a number :"))
s.add(int(number))
print(s)